//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSPConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data;
    using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
    using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

    public partial class WorkDayEntities3 : DbContext
    {
        public WorkDayEntities3()
            : base("name=WorkDayEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TaAccountLeave> TaAccountLeaves { get; set; }
        public virtual DbSet<TaLeave> TaLeaves { get; set; }
    
        public virtual ObjectResult<get_data_Result> get_data(Nullable<bool> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_data_Result>("get_data", actionParameter);
        }
        public virtual ObjectResult<get_data_Result2> get_data(Nullable<bool> action)
        {
            var actionParameter = action.HasValue ?
                new ObjectParameter("action", action) :
                new ObjectParameter("action", typeof(bool));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_data_Result2>("get_data");
        }

    }
}
